source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]

# VER documentacion en https://github.com/rails/sprockets-rails
gem 'sprockets-rails', :require => 'sprockets/railtie'
# VER documentacion en https://github.com/twbs/bootstrap-sass#a-ruby-on-rails
gem 'bootstrap-sass', '~> 3.3.5'
#gem 'sass-rails', '>= 3.2'

#https://github.com/plataformatec/simple_form
# gem 'simple_form'
# SOlUCION AL ERROR DE CLIENT SIDE VALIDATION http://stackoverflow.com/questions/21102324/the-rails-way-of-doing-client-side-validation-rails-4-with-simple-form

#https://github.com/DavyJonesLocker/client_side_validations
# gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: "4-2-stable"
# gem 'client_side_validations', :git => 'https://github.com/DavyJonesLocker/client_side_validations.git', branch: "4-2-stable"
#https://github.com/DavyJonesLocker/client_side_validations-simple_form
# gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form'
#gem 'client_side_validations-simple_form',:git => 'https://github.com/DavyJonesLocker/client_side_validations-simple_form.git'

gem 'jquery-datatables-rails', '~> 3.3.0'
gem 'ajax-datatables-rails'

gem "kaminari"
gem "to_xls"
gem 'thinreports-rails'

gem "select2-rails"

gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.37'

gem 'pg'

gem 'data-confirm-modal', github: 'ifad/data-confirm-modal'